config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  post "home/send_email"

  get "home/msales", path: "/msales"
  get "home/livestock", path: "/livestock"
  get "home/pca", path: "/pca"
  get "home/pos", path: "/pos"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def send_email
    ContactMailer.send_contact_mail(params).deliver_now
    respond_to do |format|
      format.html { redirect_to home_index_path }
      format.js
    end
  end

  def msales
  end

  def livestock
  end

  def pca
  end

  def pos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact.html.haml
%section#contact.section.contact_section.even
  .section_header.contact_section_header
    %h2.section_title.contact_section_title
      = link_to "#" do
        %span.icon.icon-envelope-alt= fa_icon "envelope"
        %span.section_name Contact
      %span.section_icon

  .section_body.contact_section_body
    #googlemap_data
      #sc_googlemap.sc_googlemap{ style: "width:100%;height:294px;" }
      .add_info
        .profile_row.header Contact info
        .profile_row.address
          %span.th Address
          %span.td
        .profile_row.email
          %span.th Email
          %span.td
        .profile_row.website
          %span.th Website
          %span.td

    .sidebar.contact_sidebar
      %aside#qrcode-vcard-widget-2.widget.widget_qrcode_vcard
        %h3.widget_title VCARD
        .widget_inner
          .qrcode

    .contact_form
      .contact_form_data
        .sc_contact_form
          %h3.title keep in touch
          %form
            .field
              %label.required Name
              %input#sc_contact_form_username{ type: "text", name: "username" }
            .field
              %label.required Email
              %input#sc_contact_form_email{ type: "text", name: "email" }
            .field.message
              %label.required Your Message
              %textarea#sc_contact_form_message{ name: "message" }
            .button
              = link_to "#", class: "enter" do
                %span Submit

          .result.sc_infobox

app/views/home/_portfolio.html.haml
%section#portfolio.section.portfolio_section.odd
  .section_header.portfolio_section_header
    %h2.section_title.portfolio_section_title
      = link_to "#" do
        %span.icon.icon-briefcase= fa_icon "briefcase"
        %span.section_name Portfolio
      %span.section_icon

  .section_body.portfolio_section_body
    .portfolio_wrapper
      %h3.title
        %span.category_title_icon.yellow
        Some of my projects

      .portfolio_items
        %article.post.portfolio_post.portfolio_post_1.first.even.category_4.category_6
          .post_pic.portfolio_post_pic
            = link_to home_msales_path, class: "w_hover img-link img-wrap" do
              %span.overlay
              %span.link-icon
              = image_tag "msales.png", alt: "msales"
          %h4.post_title
            = link_to "Al-Safi Danone", home_msales_path
          %h5.post_subtitle mSales

        %article.post.portfolio_post.portfolio_post_1.first.even.category_4.category_6
          .post_pic.portfolio_post_pic
            = link_to home_livestock_path, class: "w_hover img-link img-wrap" do
              %span.overlay
              %span.link-icon
              = image_tag "livestock.png", alt: "livestock"
          %h4.post_title
            = link_to "Al-Safi Danone", home_livestock_path
          %h5.post_subtitle Livestock Valuation

        %article.post.portfolio_post.portfolio_post_1.first.even.category_4.category_6
          .post_pic.portfolio_post_pic
            = link_to home_pca_path, class: "w_hover img-link img-wrap" do
              %span.overlay
              %span.link-icon
              = image_tag "pca.png", alt: "pca"
          %h4.post_title
            = link_to "Saudi Aramco", home_pca_path
          %h5.post_subtitle Multi-dimensional PCA

        %article.post.portfolio_post.portfolio_post_1.first.even.category_4.category_6
          .post_pic.portfolio_post_pic
            = link_to home_pos_path, class: "w_hover img-link img-wrap" do
              %span.overlay
              %span.link-icon
              = image_tag "pos.png", alt: "pos"
          %h4.post_title
            = link_to "Sony Gulf", home_pos_path
          %h5.post_subtitle POS

app/views/home/_profile.html.haml
%section#profile.section.profile_section.first.odd
  = link_to "#", id: "blog_page_link" do
    %span.icon.icon-pencil= fa_icon "pencil"
    %span.label Blog

  .section_header.profile_section_header.opened
    %h2.section_title.profile_section_title.vis
      = link_to "#" do
        %span.icon.icon-user= fa_icon "user"
        %span.section_name Profile
      %span.section_icon

    #profile_header
      #profile_user
        #profile_photo
          = image_tag "moeabdol.png"

        #profile_name_area
          #profile_name
            %h1#profile_title
              %span.firstname Mohammad
              %span.lastname Saed

            %h4#profile_position Computer Scientist

      #profile_data
        .profile_row.name
          %span.th Name:
          %span.td Mohammad Abdullah Saed
        .profile_row.birth
          %span.th Date of Birth:
          %span.td September 7, 1982
        .profile_row.address
          %span.th Address:
          %span.td Riyadh, Saudi Arabia
        .profile_row.email
          %span.th Email:
          %span.td= mail_to "mohd.a.saed@gmail.com"
        .profile_row.website
          %span.th Website:
          %span.td= link_to "http://moeabdol.com","http://moeabdol.com"

  .section_body.profile_section_body
    .profile_body
      %p
        Mohammad Abdullah (aka moeabdol), 33 years young, born in Egypt and grew
        up in Saudi Arabia. Highly motivated and creative problem solver. Finds
        joy in implementing challenging, smart solutions and sharing knowledge
        with others.
      %br
      %p
        I currently work as a freelance full-stack web developer. I spend most
        of my time crafting software and bending computer code. I'm a firm
        believer in the agile methodology, and have been learning and applying
        its principles throughout my career.
      %br
      %p
        I put great effort in producing high-quality and flexible systems that
        are well designed and easly extended. I defiantly have great
        appreciation for beautifulll code that conveys its intention clearly,
        and reads like well written pros.

app/views/home/_resume.html.haml
%section#resume.section.resume_section.even
  .section_header.resume_section_header
    %h2.section_title.resume_section_title
      = link_to "#" do
        %span.icon.icon-align-left= fa_icon "align-left"
        %span.section_name Resume
      %span.section_icon

  .section_body.resume_section_body
    .sidebar.resume_sidebar
      %aside.widget.widget_skills
        %h3.widget_title Programming skills
        .widget_iner.style_1
          .skills_row.odd.first
            %span.caption Ruby on Rails
            %span.progressbar
              %span.progress.red{ "data-process": "90%" }
                %span.value 90%

          .skills_row.even
            %span.caption Python
            %span.progressbar
              %span.progress.green{ "data-process": "95%" }
                %span.value 95%

          .skills_row.odd
            %span.caption HTML 5
            %span.progressbar
              %span.progress.blue{ "data-process": "90%" }
                %span.value 90%

          .skills_row.even
            %span.caption CSS 3
            %span.progressbar
              %span.progress.yellow{ "data-process": "80%" }
                %span.value 80%

          .skills_row.odd
            %span.caption Javascript
            %span.progressbar
              %span.progress.aqua{ "data-process": "70%" }
                %span.value 70%

      %aside.widget.widget_skills
        %h3.widget_title Engineering Skills
        .widget_inner.style_2
          .skills_row.even
            %span.legend.yellow
            %span.caption Analysis

          .skills_row.odd
            %span.legend.aqua
            %span.caption Critical Thinking

          .skills_row.odd
            %span.legend.blue
            %span.caption Design

          .skills_row.odd
            %span.legend.red
            %span.caption Quality Assurance

          .skills_row.even
            %span.legend.green
            %span.caption Time Managment

          .svg
            %svg.piechart{ xmlns: "http://www.w3.org/2000/svg" }
              %path{ d: "M66, 66 L130,66 A64,64 0 0,1 57,129 z",
                     fill: "#397ea3" }
              %path{ d: "M66,66 L57, 129 A64,64 0 0,1 2,60 z",
                     fill: "#4ca5d0" }
              %path{ d: "M66,66 L2,  60  A64,64 0 0,1 34,11 z",
                     fill: "#6ca338" }
              %path{ d: "M66,66 L34, 11  A64,64 0 0,1 103,14 z",
                     fill: "#ffbc38" }
              %path{ d: "M66,66 L103,14  A64,64 0 0,1 130,66 z",
                     fill: "#e82c0c" }
              %circle{ cx: "66", cy: "66", r: "40", fill: "#ffffff" }

      %aside.widget.widget_skills
        %h3.widget_title Language Skills
        .widget_inner.style_3
          .skills_row.odd.first
            %span.caption Arabic
            %span.progressbar
              %span.progress.red{ "data-process": "100%" }

          .skills_row.odd.even
            %span.caption English
            %span.progressbar
              %span.progress.green{ "data-process": "100%" }

          .skills_row.odd.odd
            %span.caption Japanese
            %span.progressbar
              %span.progress.yellow{ "data-process": "40%" }

    .wrapper.resume_wrapper
      .category.resume_category.resume_category_1.first.even
        .category_header.resume_category_header
          %h3.category_title
            %span.category_title_icon.aqua
            Employment

        .category_body.resume_category_body
          %article.post.resume_post.resume_post_1.first.even
            .post_header.resume_post_header
              .resume_period
                %span.period_from 2010
                \-
                %span.period_to 2012
              %h4.post_title
                %span.post_title_icon.aqua
                = link_to "Al-Faisaliah Group (Riyadh, SA)",
                          "http://www.alfaisaliah.com", target: "_blank"
              %h5.post_subtitle
                Software Developer

            .post_body.resume_post_body
              %p
                AlFaisaliah Group is a diverse conglomerate that drives
                multiple businesses across the kingdom and middle-east. During
                my career there, I have developed and maintained a plathora of
                software products serving Al-Faisaliah subsidiaries' needs;
                such as, Al-Safi Danone and Sony Gulf.
              %br
              %p
                The software I have developed spanned multiple business domains.
                From sales and marketing to cattle managment and financial
                applications. I have also introduced and developed an in-house
                application for Al-Safi financial departement to help manage
                their daily and monthly reporting of their livestock valuation.
                Its still in use until this day.

          %article.post.resume_post.resume_post_2.odd
            .post_header.resume_post_header
              .resume_period
                %span.period_from 2010
                \-
                %span.period_to 2010
              %h4.post_title
                %span.post_title_icon.aqua
                = link_to "Saudi Aramco (Dhahran, SA)",
                          "http://www.saudiaramco.com/", target: "_blank"
              %h5.post_subtitle
                Software Developer & Engineer

            .post_body.resume_post_body
              %p
                Being part of the engineering core team, I have developed
                applications using cutting-edge machine learning algorithms to
                visualize data and extract patterns from real-time data sources.
                The patterns and information revealed by my applications helped
                engineers futher optimize their processeces of Oil and Gas
                extraction.

      .category.resume_category.resume_category_2.odd
        .category_header.resume_category_header
          %h3.category_title
            %span.category_title_icon.green
            Education

        .category_body.resume_category_body
          %article.post.resume_post.resume_post_1.first.even
            .post_header.resume_post_header
              .resume_period
                %span.period_from 2012
                \-
                %span.period_to 2014
              %h4.post_title
                %span.post_title_icon.green
                = link_to "Keio University (Tokyo, JP)",
                          "http://www.keio.ac.jp", target: "_blank"
              %h5.post_subtitle
                Artificial Intelligence

            .post_body.resume_post_body
              %p
                Conducted reasearch in machine learning and computer vision.
                My research "Multi-Modal Convolutional Neural Networks" trys to
                answer the question of wither we can better infer video data
                given audio and vice-versa. The research used the best computer
                vision algorithm at the time namely, convolutional neural
                networks.

          %article.post.resume_post.resume_post_2.odd
            .post_header.resume_post_header
              .resume_period
                %span.period_from 2005
                \-
                %span.period_to 2010
              %h4.post_title
                %span.post_title_icon.green
                = link_to "Prince Sultan University (Riyadh, SA)",
                          "http://www.psu.edu.sa", target: "_blank"
              %h5.post_subtitle
                Computer Science

            .post_body.resume_post_body
              %p
                Received my BSc. of science in Computer Science.

app/views/home/index.html.haml
= render "profile"

#mainpage_accordion_area
  = render "resume"
  = render "portfolio"
  = render "contact"

app/views/home/livestock.html.haml
%section#profile.section.profile_section.first.odd
  = link_to root_path, id: "blog_page_link" do
    %span.icon= fa_icon "home"
    %span.label Home

  .section_header.project_section_header.opened
    %h2.section_title.project_section_title.vis
      %strong
        %span.icon.icon-briefcase= fa_icon "briefcase"
        %span.section_name Projects

  #primary.content_area
    #content.site_content.post_content{ role: "main" }
      %section.section.post_section.blog_section
        .section_header.post_section_header
        .section_body.post_section_body
          %article.post
            %h3.post_title Livestock Valuation

            .post_thumb
              = image_tag "livestock_pic.png", alt: "msales"

            .content_text
              %p
                = link_to "Al-Safi",
                          "http://www.alfaisaliah.com/index0f0e.html?id=125"
                farms is home to thousands of cattle. The cattle are  managed
                using an old system written in an ancient computer
                language. Everyday Al-Safi employees had to be on-site, manually
                collecting cattle data. This is very tedious and very slow given
                that by the time data is collected, processed by the system,
                and then reported; the market valuation of these livestock would
                have already changed.
              %br
              %p
                When Al-Safi wanted to introduce RFID (Radio Frequencey
                Identification) technology to speed up livestock data collection
                process, they were faced with the issue of their old system not
                being able to adapt to their new technology and requirements.
                With the help of Al-Safi's financial department, I have built an
                entire system from scratch that sits in-between the old system
                and the end-user. Reports that are generated by they old system
                would be fed into my system and then my system would generate
                financial reports that follow new business rules and
                requirements.

app/views/home/msales.html.haml
%section#profile.section.profile_section.first.odd
  = link_to root_path, id: "blog_page_link" do
    %span.icon= fa_icon "home"
    %span.label Home

  .section_header.project_section_header.opened
    %h2.section_title.project_section_title.vis
      %strong
        %span.icon.icon-briefcase= fa_icon "briefcase"
        %span.section_name Projects

  #primary.content_area
    #content.site_content.post_content{ role: "main" }
      %section.section.post_section.blog_section
        .section_header.post_section_header
        .section_body.post_section_body
          %article.post
            %h3.post_title mSales

            .post_thumb
              = image_tag "msales_screenshot.png", alt: "msales"

            .content_text
              %p
                = link_to "Al-Safi",
                          "http://www.alfaisaliah.com/index0f0e.html?id=125"
                is a world leading nutrition company. In 1998, it was
                awarded the guinness world record for being the largest
                integrated dairy farm in the world.
              %br
              %p
                One of the major software applications employed by Al-Safi is
                mSales. mSales is a sales application for Al-Safi. The main
                purpose of mSales is to keep track of all sales operations
                executed on a daily basis by Al-Safi sales men to satisfy dairy
                demands accross all Gulf countries.
              %br
              %p
                There are two main parts of the mSales application. First, The
                front-end which handles collecting sales data using handheld
                devices onboard every Safi distribution van. Second, the
                back-end application and database which handles the processing
                and storage of operations data.
              %br
              %p
                During my time with Al-Faisaliah, I worked directly with sales
                and marketing executives and personnel. Together we helped
                extend mSales and introduce new features; such as, adding
                loyalty prorams to mSales. This functionality identifies
                long-standing customers and in return offers them our products
                at cheaper prices.

app/views/home/pca.html.haml
%section#profile.section.profile_section.first.odd
  = link_to root_path, id: "blog_page_link" do
    %span.icon= fa_icon "home"
    %span.label Home

  .section_header.project_section_header.opened
    %h2.section_title.project_section_title.vis
      %strong
        %span.icon.icon-briefcase= fa_icon "briefcase"
        %span.section_name Projects

  #primary.content_area
    #content.site_content.post_content{ role: "main" }
      %section.section.post_section.blog_section
        .section_header.post_section_header
        .section_body.post_section_body
          %article.post
            %h3.post_title Principle Component Analysis

            .post_thumb
              = image_tag "pca_pic.png", alt: "msales"

            .content_text
              %p
                = link_to "Saudi Aramco",
                          "http://www.saudiaramco.com/en/home.html"
                is the world's leading energy provider. It is the richest
                company in the world with an annual revenue of US $378 billion
                (2014). It extracts crude Oil and Gas and refines them to a
                multitude of derivative products.
              %br
              %p
                Being a dinosaur of a company that it is, everything that Aramco
                employes and uses is custom-built. To give you a sense of what
                I'm talking about, take for example databases. The database
                they use in their engineering departments are neither relational
                nor document-based. They are real-time databases and are
                time-based.  That is because the company is wired to hundreds of
                refineries with hundreds of thousands of devices and sensors
                within each of these refinaries.
              %br
              %p
                The great thing was that at my department (Process and Controllers
                Systems) we had easy and instant access to millions of records
                of historical and continious real-time data. My mission was to
                extract data, discover patterns, and distill knowledge. The
                devices and sensors located at the refineries collected data
                such as temperature,humedity, pressure, etc. So at any given
                point of time, each sensor has multi-dimensional data
                attributes.
              %br
              %p
                With the help of many engineers, I have built in-house
                applications that collects, filters, cleans, and then reveals
                patterns. We had to account for noise in the data. The nose
                being the result of malfunctioning sensors and/or misadjusted
                valves and knobs on these devices. Our criterea was to discover
                abnormalities in these devices. I used the PCA (Principle
                Component Analysis) algorithm to reduce dimensionality of data
                and reveal data with highest variance. High variance demonstrate
                instability in the device reporting these data, this can be due
                to misadjustment (which gets fixed) or malfunction (which gets
                replaced). Having done so this technique is proactive as it
                help reveals problems in the field before it gets any more
                serious.

app/views/home/pos.html.haml
%section#profile.section.profile_section.first.odd
  = link_to root_path, id: "blog_page_link" do
    %span.icon= fa_icon "home"
    %span.label Home

  .section_header.project_section_header.opened
    %h2.section_title.project_section_title.vis
      %strong
        %span.icon.icon-briefcase= fa_icon "briefcase"
        %span.section_name Projects

  #primary.content_area
    #content.site_content.post_content{ role: "main" }
      %section.section.post_section.blog_section
        .section_header.post_section_header
        .section_body.post_section_body
          %article.post
            %h3.post_title Point of Sales

            .post_thumb
              = image_tag "mec.jpg", alt: "msales"

            .content_text
              %p
                = link_to "Modern Electronics Company",
                          "http://alfaisaliah.com/afg2/?p=5213#"
                (foremerly Sony Gulf) initiated a
                major project to replace all their traditional casheir systems
                located at their outlets with digital point of sales systems.
                The new POS system is integrated with SAP ERP system as the
                back-end, so sales information would flow back and forth
                instantly. Any sales information would flow to the back-end and
                higher management can now make instant marketing, sales, and
                financial decisions. On the other hand when decisions are made
                the rules flow down again to the front-end reflecting the latest
                decisions made by management.
              %br
              %p
                During this project I was MEC's technical consultant. Having to
                deal with all technical aspects of the project starting from
                which POS system to acquire, making available the digital
                infrastructure for the project, shaping and gathering
                requirements with MEC's management and finally communicating
                with SAP's team on our back-end requirements.

app/views/home/send_email.js.haml
jQuery(".sc_contact_form .result").toggleClass("sc_infobox_style_error", false).toggleClass("sc_infobox_style_success", false);
jQuery(".sc_contact_form .result").addClass("sc_infobox_style_success").html("Your message is sent! Thank you.");
setTimeout("jQuery('.sc_contact_form .result').fadeOut(); jQuery('.sc_contact_form form').get(0).reset();", 3000);

app/views/layouts/application.html.haml
!!! 5
%html{ lang: "en-US" }
  %head
    %meta{ charset: "UTF-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1" }
    %title moeabdol
    = favicon_link_tag "/favicon.ico?version=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
    = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js")
    = csrf_meta_tags

  %body.home.blog.dark
    .switherHead
    .colored
      .blue
      .aqua
      .green
      .yellow
      .red

    #page.hfeed.site
      %header#header.site_header{ role: "banner" }
        .social_buttons
          %ul
            %li
              = link_to "http://stackoverflow.com/users/667127/moeabdol",
                        title: "Stackoverflow", target: "_blank" do
                = fa_icon "stack-overflow"
            %li
              = link_to "https://github.com/moeabdol",
                        title: "Github", target: "_blank" do
                = fa_icon "github"
            %li
              = link_to "https://jp.linkedin.com/in/mohammadsaed",
                        title: "Linkedin", target: "_blank" do
                = fa_icon "linkedin"
            %li
              = link_to "https://twitter.com/moeabdol",
                        title: "Twitter", target: "_blank" do
                = fa_icon "twitter"

      #main
        #primary.content_area
          #content.site_content{ role: "main" }
            = yield

    %footer#footer.site_footer{ role: "contentinfo" }
      .footer_copyright
        moeabdol.com &copy;
        = Time.now.strftime("%Y")